version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - docker build -t awslearning333/docker-react-1 Dockerfile .
artifacts:
  files:
    - '**/*'

