sudo: required
services:
  - docker


before_install:
  - docker bulid -t awslearning333/docker-react-1 -f Dockerfile.dev .


script:
  - docker run -e CI=true awslearning333/docker-react-1 npm run test

