apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs
  labels:
    app: reactjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
        - name: devopshint
          image: $TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
