on: push
 

jobs:
 
  build:
   
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA5TOIR5JB6IZATMG5
        aws-secret-access-key: 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
        aws-region: us-east-2

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 935112862275.dkr.ecr.us-east-2.amazonaws.com

    - name: Build and Push
      run: |
        echo Build started on $(date)
        TAG=$(date +'%Y%m%d_%H%M%S')
        echo Building the Docker image with tag $TAG...
        docker build -t reactjs:$TAG .
        docker tag reactjs:$TAG 935112862275.dkr.ecr.us-east-2.amazonaws.com/testing:$TAG
        docker push 935112862275.dkr.ecr.us-east-2.amazonaws.com/testing:$TAG
        echo "TAG=$TAG" >> $GITHUB_ENV
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Update kube config
      run: |
        set -x  # Enable debugging
        aws eks update-kubeconfig --name test1
        set +x  # disable debugging
        sed -i "s|TAG|${{ env.TAG }}|g" deployment.yml
        cat deployment.yml

    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
